AWSTemplateFormatVersion: '2010-09-09'
Description: A simple VPC setup with public and private subnets, an Internet Gateway, and a NAT Gateway.

Resources:
# vpc
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties: 
      CidrBlock: '10.0.0.0/16'
      Tags:
        - Key: Name
          Value: Nabeelvpc
 # InternetGateway         
  MyInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: Nabeel-InternetGateway
          # Attach Internet Gateway to VPC
  MyVPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: vpc-0a7b63d5b26578c6d
      InternetGatewayId: igw-0e4324bf13f4d68ec
      # Public Subnet 1
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: vpc-0a7b63d5b26578c6d
      CidrBlock: '10.0.1.0/24'
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: PublicSubnet1
# Public Subnet 2
  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: vpc-0a7b63d5b26578c6d
      CidrBlock: '10.0.2.0/24'
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: PublicSubnet2
          # Private Subnet 1
  PrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: vpc-0a7b63d5b26578c6d
      CidrBlock: '10.0.3.0/24'
      Tags:
        - Key: Name
          Value: PrivateSubnet1
          # Private Subnet 2
  PrivateSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: vpc-0a7b63d5b26578c6d
      CidrBlock: '10.0.4.0/24'
      Tags:
        - Key: Name
          Value: PrivateSubnet2
           # Public Route Table
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: vpc-0a7b63d5b26578c6d
      Tags:
        - Key: Name
          Value: PublicRouteTable 




