AWSTemplateFormatVersion: '2010-09-09'
Description: A simple VPC setup with public and private subnets, an Internet Gateway, and a NAT Gateway.

Resources:
# vpc
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties: 
      CidrBlock: '10.0.0.0/16'
      Tags:
        - Key: Name
          Value: Nabeelvpc
 # InternetGateway         
  MyInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: Nabeel-InternetGateway
